apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: hn-tldr-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: backend-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef:
            name: hn-tldr-config
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: hn-tldr-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: hn-tldr-test
spec:
  selector:
    app: backend-api
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: LoadBalancer
