apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hn-tldr-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: hn-tldr-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hn-tldr-test
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 7003
    targetPort: 3000
  type: LoadBalancer
