apiVersion: v1
kind: PersistentVolume
metadata:
  name: hn-tldr-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /tmp/hn-tldr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hn-tldr-data-pvc
  namespace: hn-tldr-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
